version: '3.8'

services:
  db:
    image: postgres:17
    container_name: rooming-list-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: rooming-list-be
    env_file: ./backend/.env 
    depends_on:
      - db
    ports:
      - "${BE_PORT}:${BE_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  pgdata:
